version: '3.8'
services:
  jenkins:
    image: devops-jenkins
    user: root
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    privileged: true
    volumes:
      - jenkins_home:/var/jenkins_home
      - "C:/Users/hp/.kube:/var/jenkins_home/.kube"
      # Removed Windows kubectl mount (will install Linux binary inside container)
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=true
      - KUBECONFIG=/var/jenkins_home/.kube/config
      - MINIKUBE_IN_DOCKER=true
      - DOCKER_HOST=unix:///var/run/docker.sock
      - MINIKUBE_DRIVER=docker
volumes:
  jenkins_home:
