apiVersion: v1
kind: Pod
metadata:
  name: oom-pod
spec:
  restartPolicy: Never
  containers:
  - name: oom-pod
    image: polinux/stress
    resources:
      limits:
        memory: "50Mi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]